//go:build ignore

// generate_model_catalog.go converts the models.dev API snapshot
// (https://models.dev/api.json) into an embedded Go catalog for the
// pi-go model picker and compaction budgets.
//
// Usage:
//
//	go run scripts/generate_model_catalog.go -in /tmp/models-dev.json -out pkg/provider/modelcatalog/catalog_gen.go
//	go run scripts/generate_model_catalog.go -fetch              # download first
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"
)

// providers pi-go can actually resolve (see pkg/provider/factory.go).
var wanted = map[string]string{
	"anthropic":   "anthropic",
	"openai":      "openai",
	"openrouter":  "openrouter",
	"groq":        "groq",
	"deepseek":    "deepseek",
	"google":      "gemini",
	"xai":         "xai",
	"opencode-go": "opencode-go",
	"mistral":     "mistral",
	"cerebras":    "cerebras",
}

type mdModel struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Reasoning bool   `json:"reasoning"`
	Limit     struct {
		Context int `json:"context"`
		Output  int `json:"output"`
	} `json:"limit"`
	Cost struct {
		Input  float64 `json:"input"`
		Output float64 `json:"output"`
	} `json:"cost"`
	Modalities struct {
		Input []string `json:"input"`
	} `json:"modalities"`
}

type mdProvider struct {
	Models map[string]mdModel `json:"models"`
}

func main() {
	in := flag.String("in", "", "path to models.dev api.json snapshot")
	fetch := flag.Bool("fetch", false, "download https://models.dev/api.json first")
	out := flag.String("out", "pkg/provider/modelcatalog/catalog_gen.go", "output Go file")
	flag.Parse()

	raw := []byte{}
	var err error
	if *fetch {
		client := &http.Client{Timeout: 60 * time.Second}
		resp, e := client.Get("https://models.dev/api.json")
		if e != nil {
			fatal("fetch: %v", e)
		}
		defer resp.Body.Close()
		if resp.StatusCode != 200 {
			fatal("fetch: HTTP %d", resp.StatusCode)
		}
		raw, err = io.ReadAll(resp.Body)
		resp.Body.Close()
		if err != nil {
			fatal("fetch read: %v", err)
		}
	} else {
		if *in == "" {
			fatal("pass -in <file> or -fetch")
		}
		raw, err = os.ReadFile(*in)
		if err != nil {
			fatal("read: %v", err)
		}
	}

	var catalog map[string]mdProvider
	if err := json.Unmarshal(raw, &catalog); err != nil {
		fatal("parse models.dev json: %v", err)
	}

	type entry struct {
		prov, id, name     string
		ctx, maxOut        int
		inCost, outCost    float64
		reasoning, imageIn bool
	}
	var entries []entry
	total := 0
	for devID, goProv := range wanted {
		p, ok := catalog[devID]
		if !ok {
			continue
		}
		for id, m := range p.Models {
			if m.Limit.Context <= 0 {
				continue // no usable metadata
			}
			name := m.Name
			if name == "" {
				name = id
			}
			e := entry{prov: goProv, id: id, name: name, ctx: m.Limit.Context, maxOut: m.Limit.Output, inCost: m.Cost.Input, outCost: m.Cost.Output, reasoning: m.Reasoning}
			for _, mo := range m.Modalities.Input {
				if mo == "image" || mo == "pdf" {
					e.imageIn = true
				}
			}
			entries = append(entries, e)
			total++
		}
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].prov != entries[j].prov {
			return entries[i].prov < entries[j].prov
		}
		return entries[i].id < entries[j].id
	})

	var sb strings.Builder
	sb.WriteString(`// Code generated by scripts/generate_model_catalog.go from models.dev. DO NOT EDIT.
// Regenerate: go run scripts/generate_model_catalog.go -fetch

package modelcatalog

`)
	sb.WriteString("var generatedCatalog = []ModelInfo{\n")
	for _, e := range entries {
		sb.WriteString(fmt.Sprintf("\t{Provider: %q, ID: %q, Name: %q, ContextWindow: %d, MaxOutput: %d, InputCost: %.4f, OutputCost: %.4f, Reasoning: %v, ImageInput: %v},\n",
			e.prov, e.id, e.name, e.ctx, e.maxOut, e.inCost, e.outCost, e.reasoning, e.imageIn))
	}
	sb.WriteString("}\n")

	src := sb.String()
	formatted, err := format.Source([]byte(src))
	if err != nil {
		fatal("gofmt generated: %v", err)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fatal("write: %v", err)
	}
	fmt.Printf("wrote %s: %d models across %d providers\n", *out, total, len(wanted))
}

func readAll(resp *http.Response) ([]byte, error) {
	defer resp.Body.Close()
	var sb strings.Builder
	buf := make([]byte, 1<<20)
	for {
		n, err := resp.Body.Read(buf)
		sb.Write(buf[:n])
		if err != nil {
			if err.Error() == "EOF" {
				return []byte(sb.String()), nil
			}
			return nil, err
		}
	}
}

func fatal(f string, a ...any) {
	fmt.Fprintf(os.Stderr, f+"\n", a...)
	os.Exit(1)
}
